name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v1

        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8

        - name: Install pelican with markdown
          shell: bash
          run: "pip install invoke pelican[markdown]"

        - name: Set up pelican and dependencies
          shell: bash
          run: "pip install -r requirements.txt"

        - name: Build the project
          shell: bash
          run: "pelican content -s publishconf.py -t theme/basic/ --relative-urls"

        - name: Rm useless article content
          shell: bash
          run: "rm -rf output/content/*"

        - name: Rm useless article content
          shell: bash
          run: "rm -rf output/patois*"

        - name: Rm useless article content
          shell: bash
          run: "rm -rf output/francais*"

        - name: Check if we have everything
          shell: bash
          run: "ls -la output/"

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: output # The folder the action should deploy.
